"""Summit TPE transfer-calculator API. Thin REST wrapper around
projection.py + the summit_tpe_cache.sqlite built by build_cache.py --
simple enough for a website today and a mobile app later, since both just
speak JSON over HTTP rather than needing this logic ported into each
client.
 
Run:
    uvicorn api:app --reload --port 8000
 
Then, e.g.:
    GET /players?search=troxell
    GET /teams?tier=High-Major
    GET /teams/4/roles
    GET /project?player_id=1234&target_team_id=4&minutes=28
    GET /project?player_id=1234&target_team_id=4&role=starter
 
Interactive docs (auto-generated by FastAPI) at /docs once it's running.
 
---- Access control (env-driven, safe by default for local dev) ----
 
Two env vars control who can reach this API once it's not just running on
your own machine:
 
  SUMMIT_TPE_API_KEY
      If set, every route except /health requires a matching
      "X-API-Key: <value>" request header, or it 401s. If UNSET (the
      default), no key is required at all -- so local `curl`/`/docs`
      testing keeps working with zero setup. Generate one with e.g.
      `python -c "import secrets; print(secrets.token_urlsafe(32))"` and
      set it as an environment variable on whatever host runs this, then
      give the same value to your frontend to send on every request.
 
  SUMMIT_TPE_ALLOWED_ORIGINS
      Comma-separated list of origins allowed to call this API from a
      browser (e.g. "https://mysite.com,https://www.mysite.com"). Defaults
      to "*" (any origin) for local dev. Set this to your real domain(s)
      before a real website points at this API -- "*" plus no API key is
      an open API to the entire internet.
 
Neither is required to run this locally. Both print a startup warning if
left at their insecure defaults, so it's obvious in the logs (not just in
this docstring) that they haven't been configured yet.
"""
 
import os
import secrets
import sqlite3
from pathlib import Path
 
from fastapi import Body, Depends, FastAPI, Header, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
 
from projection import (
    CATEGORY_INFO, LEADERBOARD_STATS, OPPONENT_SPLIT_STATS, ProjectionError, ROLE_NAMES, VALID_LEVELS,
    back_half_leaderboard, conference_standings, find_fits, game_detail, leaderboard, leap_candidates,
    opponent_split_leaderboard, player_game_logs, player_splits, player_trajectory, project_batch,
    project_player, standout_projections, team_needs, team_roles, team_schedule,
)
from summit_calc import TIER_ABBREV, normalize_tier
 
DB_PATH = Path(__file__).parent / "summit_tpe_cache.sqlite"
 
API_KEY = os.environ.get("SUMMIT_TPE_API_KEY") or None
ALLOWED_ORIGINS = [o.strip() for o in os.environ.get("SUMMIT_TPE_ALLOWED_ORIGINS", "*").split(",") if o.strip()] or ["*"]
 
app = FastAPI(title="Summit TPE API", version="1.0")
 
app.add_middleware(
    CORSMiddleware, allow_origins=ALLOWED_ORIGINS, allow_methods=["GET", "POST"], allow_headers=["*"],
)
 
 
@app.on_event("startup")
def _warn_if_insecure():
    if API_KEY is None:
        print("[summit-tpe-api] WARNING: SUMMIT_TPE_API_KEY is not set -- every route is open to "
              "anyone who can reach this host. Fine for local dev, not fine once this is reachable "
              "from the internet.")
    if ALLOWED_ORIGINS == ["*"]:
        print("[summit-tpe-api] WARNING: SUMMIT_TPE_ALLOWED_ORIGINS is not set -- CORS allows "
              "requests from ANY website. Set it to your real domain(s) before going live.")
 
 
def require_api_key(x_api_key: str | None = Header(None)):
    """FastAPI dependency, applied to every route below except /health.
    No-ops entirely if SUMMIT_TPE_API_KEY isn't set (local dev default)."""
    if API_KEY is None:
        return
    if x_api_key is None or not secrets.compare_digest(x_api_key, API_KEY):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
 
 
def get_conn():
    if not DB_PATH.exists():
        raise HTTPException(status_code=503, detail=f"{DB_PATH.name} not found -- run build_cache.py first.")
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn
 
 
@app.get("/health")
def health():
    exists = DB_PATH.exists()
    season = None
    if exists:
        conn = get_conn()
        row = conn.execute("SELECT value FROM meta WHERE key='season'").fetchone()
        season = row[0] if row else None
        conn.close()
    return {"ok": exists, "cache_present": exists, "season": season}
 
 
@app.get("/teams", dependencies=[Depends(require_api_key)])
def list_teams(
    tier: str | None = Query(None, description=f"Filter by tier: one of {list(VALID_LEVELS)} "
                                                 f"(\"P5\" is still accepted as an alias for High-Major)."),
    conference: str | None = Query(None),
    search: str | None = Query(None, description="Case-insensitive substring match on team name"),
    limit: int = Query(100, le=500),
    offset: int = 0,
):
    conn = get_conn()
    tier = normalize_tier(tier)
    clauses, params = [], []
    if tier:
        clauses.append("tier = ?")
        params.append(tier)
    if conference:
        clauses.append("conference = ?")
        params.append(conference)
    if search:
        clauses.append("name LIKE ?")
        params.append(f"%{search}%")
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    rows = conn.execute(
        f"SELECT team_id, name, division, conference, tier, current_rating, sos "
        f"FROM teams {where} ORDER BY current_rating DESC LIMIT ? OFFSET ?",
        params + [limit, offset],
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]
 
 
@app.get("/teams/{team_id}", dependencies=[Depends(require_api_key)])
def get_team_detail(team_id: int):
    conn = get_conn()
    row = conn.execute("SELECT * FROM teams WHERE team_id = ?", (team_id,)).fetchone()
    conn.close()
    if row is None:
        raise HTTPException(status_code=404, detail=f"No team with id {team_id}")
    return dict(row)
 
 
@app.get("/teams/{team_id}/roles", dependencies=[Depends(require_api_key)])
def get_team_roles(team_id: int):
    """Role-based minutes for this team, computed from its own current
    roster (Starter/Sixth Man/Role Player/Depth Piece) -- lets a UI show a
    coach e.g. 'Starter (31.2 min)' as a pickable option before running
    /project with role=starter, instead of only a free-text minutes field."""
    conn = get_conn()
    team = conn.execute("SELECT team_id, name FROM teams WHERE team_id = ?", (team_id,)).fetchone()
    if team is None:
        conn.close()
        raise HTTPException(status_code=404, detail=f"No team with id {team_id}")
    roles = team_roles(conn, team_id)
    conn.close()
    # team_roles() already includes team_id in its return dict -- passing
    # team_id=team_id here too used to raise "dict() got multiple values
    # for keyword argument 'team_id'" on EVERY call (found by actually
    # exercising this endpoint against the live cache, not just reading
    # the code -- it 500'd for every team tested, not just some).
    return dict(team_name=team["name"], **roles)
 
 

# Columns the /players list is allowed to sort on -- a whitelist, not a
# raw pass-through of the `sort` query param, so it can never be used to
# inject arbitrary SQL via ORDER BY (string-interpolated below since sqlite3
# params can't parameterize a column/direction name). Maps the public sort
# key to the real column to order by (hoop_score sorts on the unclamped
# hoop_score_raw, same reasoning as the default order -- see below).
PLAYERS_SORT_COLUMNS = {
    "name": "p.name", "team_name": "t.name", "tier": "t.tier", "position": "p.position",
    "class_year": "p.class_year", "games": "p.games", "ppg": "p.ppg", "rpg": "p.rpg",
    "apg": "p.apg", "bpg": "p.bpg", "spg": "p.spg", "topg": "p.topg",
    "hoop_score": "p.hoop_score_raw", "height": "p.height", "height_in": "p.height_in",
}


@app.get("/players", dependencies=[Depends(require_api_key)])
def list_players(
    search: str | None = Query(None, description="Case-insensitive substring match on player name"),
    team_id: int | None = None,
    position: str | None = Query(None, description="Exact match, e.g. G/F/C."),
    class_year: str | None = Query(None, description="Exact match, e.g. FR/SO/JR/SR/GR."),
    min_height_in: int | None = Query(None, description="Minimum height in total inches (inclusive). "
                                                          "Players with no parseable height on record are excluded "
                                                          "whenever either height bound is given."),
    max_height_in: int | None = Query(None, description="Maximum height in total inches (inclusive). Same "
                                                          "exclusion note as min_height_in."),
    sort: str | None = Query(None, description=f"Column to sort by, one of {list(PLAYERS_SORT_COLUMNS)}. "
                                                 f"Omit for the default (Summit Score, best first)."),
    order: str = Query("desc", description="asc or desc. Ignored if `sort` is omitted."),
    limit: int = Query(50, le=500),
    offset: int = 0,
):
    conn = get_conn()
    clauses, params = [], []
    if search:
        clauses.append("p.name LIKE ?")
        params.append(f"%{search}%")
    if team_id is not None:
        clauses.append("p.team_id = ?")
        params.append(team_id)
    if position:
        clauses.append("p.position = ?")
        params.append(position)
    if class_year:
        clauses.append("p.class_year = ?")
        params.append(class_year)
    if min_height_in is not None:
        clauses.append("p.height_in >= ?")
        params.append(min_height_in)
    if max_height_in is not None:
        clauses.append("p.height_in <= ?")
        params.append(max_height_in)
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""

    if sort is not None:
        if sort not in PLAYERS_SORT_COLUMNS:
            raise HTTPException(status_code=422, detail=f"sort must be one of {list(PLAYERS_SORT_COLUMNS)}, got {sort!r}.")
        direction = "ASC" if str(order).lower() == "asc" else "DESC"
        # thin_sample rows still sort after full-sample rows for any column
        # (not just the default hoop_score order) -- clicking "PPG" shouldn't
        # let a 2-minute cameo's inflated per-game rate jump to the top.
        order_by = f"COALESCE(p.thin_sample, 0) ASC, {PLAYERS_SORT_COLUMNS[sort]} {direction}"
    else:
        order_by = "COALESCE(p.thin_sample, 0) ASC, p.hoop_score_raw DESC"

    rows = conn.execute(
        # Sort by hoop_score_raw (unclamped), not hoop_score (the displayed,
        # 30-99-clamped value) -- several distinct elite seasons legitimately
        # round to the same displayed 99.0 by design (see summit_calc.py's
        # scale_to_hoopscore), so sorting on the displayed value ties players
        # who aren't actually tied and orders them arbitrarily.
        #
        # thin_sample players (see build_cache.py -- below the games/minutes
        # threshold, or a placeholder row with no game logs at all this
        # season) sort AFTER every full-sample player instead of being
        # excluded outright -- this endpoint is the site's directory/search,
        # so every rostered player needs to be findable here (that's the
        # whole point of including them in the cache at all), just not
        # crowding out real, well-evidenced seasons in the default browse
        # order. NULLS LAST on hoop_score_raw DESC handles the zero-game
        # placeholder rows, which have no computed score at all.
        f"""SELECT p.player_id, p.name, p.height, p.height_in, p.team_id, t.name AS team_name, t.tier, p.position,
                   p.class_year, p.games, p.total_minutes, p.ppg, p.rpg, p.apg, p.bpg, p.spg, p.topg,
                   p.hoop_score, p.thin_sample
            FROM players p LEFT JOIN teams t ON p.team_id = t.team_id
            {where}
            ORDER BY {order_by}
            LIMIT ? OFFSET ?""",
        params + [limit, offset],
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]
 
 
@app.get("/players/{player_id}", dependencies=[Depends(require_api_key)])
def get_player_detail(player_id: int):
    conn = get_conn()
    row = conn.execute(
        """SELECT p.*, t.name AS team_name, t.tier AS team_tier
           FROM players p LEFT JOIN teams t ON p.team_id = t.team_id
           WHERE p.player_id = ?""",
        (player_id,),
    ).fetchone()
    if row is None:
        conn.close()
        raise HTTPException(status_code=404, detail=f"No player with id {player_id}")
    result = dict(row)

    # National percentile for Summit Score -- computed live off hoop_score_raw
    # (unclamped) rather than the displayed/clamped hoop_score, same reasoning
    # as the leaderboard sort fix: gives real separation among players who'd
    # otherwise show the same rounded displayed score. Gives coaches/scouts
    # context for what the number actually means (e.g. "Top 4% of Division I"),
    # which matters more now that far fewer players show a flat 99.
    #
    # Comparison pool excludes thin_sample players (see build_cache.py) --
    # comparing against a pool diluted by small, noisy samples would make
    # the percentile less meaningful for everyone, including thin_sample
    # players themselves (whose own percentile is still shown, just judged
    # against the same real, well-evidenced season pool a full-sample
    # player is judged against).
    if result.get("hoop_score_raw") is not None:
        total = conn.execute(
            "SELECT COUNT(*) AS c FROM players WHERE (thin_sample IS NULL OR thin_sample = 0)"
        ).fetchone()["c"]
        better = conn.execute(
            "SELECT COUNT(*) AS c FROM players WHERE hoop_score_raw > ? "
            "AND (thin_sample IS NULL OR thin_sample = 0)", (result["hoop_score_raw"],)
        ).fetchone()["c"]
        # "Top X%" semantics -- rank 1 of 3,899 reads as Top 0.03%, not Top 100%.
        # 2 decimals, not 1 -- at 1 decimal, "Top 0.0%" is indistinguishable
        # for dozens of players near the very top of a ~3,900-player pool.
        result["national_percentile"] = round(100 * (better + 1) / total, 2) if total else None
    else:
        result["national_percentile"] = None

    conn.close()
    return result
 
 
@app.get("/project", dependencies=[Depends(require_api_key)])
def project(
    player_id: int,
    target_team_id: int,
    minutes: float | None = Query(None, description="Exact coach-specified minutes (0-40). Wins over "
                                                       "`role` if both are given."),
    role: str | None = Query(None, description=f"One of {ROLE_NAMES} -- resolved from the target team's "
                                                 f"own current roster via /teams/{{id}}/roles. Ignored if "
                                                 f"`minutes` is also given."),
):
    conn = get_conn()
    try:
        result = project_player(conn, player_id, target_team_id, minutes_override=minutes, role=role)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
    return result
 
 
@app.get("/teams/{team_id}/needs", dependencies=[Depends(require_api_key)])
def get_team_needs(
    team_id: int,
    top_n: int = Query(3, ge=1, le=len(CATEGORY_INFO), description="How many weakest categories to call out"),
    level: str | None = Query(
        None, description=f"One of {list(VALID_LEVELS)} (\"P5\" still accepted as an alias for High-Major). "
                           f"Restrict the comparison group to teams at that tier only, instead of the whole "
                           f"league (default). E.g. level=Low-Major judges a Low-Major team's weaknesses "
                           f"against other Low-Major rosters, not High-Major ones."),
):
    """This team's roster-weighted stat profile (rebounding, assists,
    blocks, steals, turnovers, shooting) vs. a peer group (whole league by
    default, or one tier if `level` is given), ranked worst-to-best. Feeds
    /teams/{team_id}/fits' default `stat` (that internal call always uses
    the whole league, regardless of what's passed here)."""
    conn = get_conn()
    try:
        return team_needs(conn, team_id, top_n=top_n, level=level)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
 
 
@app.get("/teams/{team_id}/fits", dependencies=[Depends(require_api_key)])
def get_team_fits(
    team_id: int,
    stat: str | None = Query(None, description=f"One of {list(CATEGORY_INFO)}. Omit to auto-pick this "
                                                 f"team's single biggest weakness from /teams/{{id}}/needs "
                                                 f"(that auto-pick is always league-wide, regardless of `level`). "
                                                 f"Ignored if `stats` is also given."),
    stats: list[str] | None = Query(
        None, description=f"Repeat for more than one category at once, e.g. "
                           f"?stats=per40_reb&stats=per40_blk -- one of {list(CATEGORY_INFO)} each. Ranks by "
                           f"the average of each candidate's league-wide z-score across all given categories "
                           f"(sign-flipped for turnovers) instead of a single raw value. Wins over `stat`."),
    limit: int = Query(15, le=100),
    min_games: int = Query(5, description="Exclude candidates with a thinner sample than this many games"),
    transfer_portal_only: bool = Query(
        False, description="Only include candidates confirmed in the transfer portal. Requires a "
                            "'Transfer Portal' column on the Players sheet + a rebuilt cache -- errors "
                            "clearly (404) if no transfer portal data has been loaded yet, instead of "
                            "silently returning an empty list."),
    level: str | None = Query(
        None, description=f"One of {list(VALID_LEVELS)} (\"P5\" still accepted as an alias for High-Major). "
                           f"Only consider candidates whose CURRENT team is at that tier -- e.g. "
                           f"level=Low-Major for a Low-Major team excludes every High-Major/Mid-Major "
                           f"player from the pool outright, instead of just labeling them."),
    role: str | None = Query(None, description=f"One of {ROLE_NAMES} -- resolved from THIS team's (team_id's) "
                                                f"own current roster via /teams/{{id}}/roles, and applied to "
                                                f"every candidate's projection. Ignored if `minutes` is given."),
    minutes: float | None = Query(None, description="Exact 0-40 minutes applied to every candidate's "
                                                      "projection. Wins over `role` if both are given."),
    class_year: str | None = Query(None, description="Exact match, e.g. FR/SO/JR/SR/GR. Restrict the "
                                                       "candidate pool to one eligibility class."),
    position: str | None = Query(None, description="Exact match, e.g. G/F/C. Restrict the candidate pool "
                                                     "to one position."),
):
    """Reverse lookup: every player NOT on this roster, ranked by her
    PROJECTED contribution to `stat`/`stats` (or this team's biggest
    weakness, if neither is given) if she transferred in, optionally
    projected at a specific role or exact minutes on THIS team rather
    than each candidate's own auto-projected minutes. Each candidate is
    projected with the exact same math as /project, just run over the
    whole player pool at once. Every candidate includes current_division,
    current_tier/level, and class_year. By default this is a plain ranking
    by projected production, not filtered by recruiting realism -- pass
    `level` to restrict the candidate pool to one tier instead of just
    labeling unrealistic candidates (a High-Major starter, etc) for manual
    skip, and/or `class_year`/`position` to narrow to a specific
    eligibility window or position."""
    conn = get_conn()
    try:
        return find_fits(conn, team_id, stat=stat, stats=stats, limit=limit, min_games=min_games,
                          transfer_portal_only=transfer_portal_only, level=level, role=role, minutes=minutes,
                          class_year=class_year, position=position)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
 
 
@app.get("/teams/{team_id}/leap-candidates", dependencies=[Depends(require_api_key)])
def get_team_leap_candidates(
    team_id: int,
    role: str | None = Query(None, description=f"One of {ROLE_NAMES} -- resolved from THIS team's (team_id's) "
                                                 f"own current roster via /teams/{{id}}/roles, applied to every "
                                                 f"candidate's projection. Ignored if `minutes` is given. Omit "
                                                 f"both for each candidate's own auto-projected minutes."),
    minutes: float | None = Query(None, description="Exact 0-40 minutes applied to every candidate's "
                                                      "projection. Wins over `role` if both are given."),
    limit: int = Query(8, le=30),
    min_games: int = Query(5, description="Exclude candidates with a thinner sample than this many games"),
):
    """'Who would make the biggest jump in Summit Score if she transferred
    here and played this role' -- every player NOT on this roster, ranked
    by the DELTA between her current Summit Score and her projected Summit
    Score at team_id (not by raw projected value the way /teams/{team_id}/
    fits ranks). Powers the team profile page's role-picker section
    (Starter/Sixth Man/Role Player/Depth Piece) -- pick a role and see
    which outside players would gain the most by transferring in and
    playing it. See leap_candidates()'s docstring for why results are
    sampled from a top pool rather than a frozen top-N list."""
    conn = get_conn()
    try:
        return leap_candidates(conn, team_id, role=role, minutes=minutes, limit=limit, min_games=min_games)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()


class BatchPlayerRequest(BaseModel):
    player_id: int
    minutes: float | None = None
    role: str | None = None
 
 
class BatchProjectRequest(BaseModel):
    target_team_id: int
    players: list[BatchPlayerRequest]
 
 
@app.post("/project/batch", dependencies=[Depends(require_api_key)])
def project_batch_endpoint(body: BatchProjectRequest = Body(...)):
    """Project several players at the same target team in one call, plus
    a combined per-game total across all of them -- for evaluating a
    shortlist of transfer targets against open roster spots at once,
    instead of one /project call per name. See project_batch()'s
    docstring for exactly what the combined total does and doesn't mean
    (it's a sum of individual projections, not a re-solved team rating)."""
    conn = get_conn()
    try:
        result = project_batch(
            conn, body.target_team_id,
            [dict(player_id=p.player_id, minutes=p.minutes, role=p.role) for p in body.players],
        )
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
    return result
 
 
@app.get("/players/{player_id}/trajectory", dependencies=[Depends(require_api_key)])
def get_player_trajectory(player_id: int):
    """Season-by-season profile for this player across every season in
    the workbook (not just the current one), with a simple Improving /
    Declining / Stable label -- for telling apart two players with a
    similar current-season line but very different trends."""
    conn = get_conn()
    try:
        return player_trajectory(conn, player_id)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()

@app.get("/leaderboards/players", dependencies=[Depends(require_api_key)])
def get_player_leaderboard(
    stat: str = Query("hoop_score", description=f"One of {list(LEADERBOARD_STATS)}."),
    level: str | None = Query(None, description=f"One of {list(VALID_LEVELS)}. Omit for the whole league."),
    division: str | None = Query(None, description="D1 or D2 (as recorded on the Teams sheet). Omit for both."),
    conference: str | None = Query(None, description="Exact conference name match. Omit for all conferences."),
    min_games: int = Query(5, description="Exclude players with a thinner sample than this many games."),
    limit: int = Query(25, le=100),
):
    """A real, no-projection leaderboard -- top players this season by one
    stat (or lowest, for turnovers), optionally restricted to a tier,
    division, and/or conference. This is what actually happened, not a
    what-if."""
    conn = get_conn()
    try:
        return leaderboard(conn, stat=stat, level=level, division=division, conference=conference,
                            min_games=min_games, limit=limit)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()


@app.get("/conferences", dependencies=[Depends(require_api_key)])
def list_conferences():
    """Every distinct conference name in the current cache, alphabetical --
    used to populate a conference filter/multiselect dropdown without the
    frontend having to derive the list itself from a full /teams fetch."""
    conn = get_conn()
    rows = conn.execute(
        "SELECT DISTINCT conference FROM teams WHERE conference IS NOT NULL ORDER BY conference"
    ).fetchall()
    conn.close()
    return [r[0] for r in rows]


@app.get("/leaderboards/standouts", dependencies=[Depends(require_api_key)])
def get_standouts_leaderboard(
    level: str = Query(..., description=f"One of {list(VALID_LEVELS)} -- the level these players currently play at."),
    target_level: str = Query("High-Major", description=f"One of {list(VALID_LEVELS)} -- the level to project them at."),
    min_games: int = Query(8, description="Exclude players with a thinner sample than this many games."),
    limit: int = Query(20, le=100),
):
    """'Who from a lower level projects best at the top level' -- every
    player currently at `level`, projected against a SYNTHETIC team at
    `target_level` (the live average current_rating of every real team at
    that tier this season, not any single school), ranked by projected
    Hoop Score. See synthetic_target_note in the response for exactly
    what was used -- this is a directional read, not a projection at any
    specific real program."""
    conn = get_conn()
    try:
        return standout_projections(conn, level=level, target_level=target_level,
                                     min_games=min_games, limit=limit)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()


@app.get("/leaderboards/opponent-splits", dependencies=[Depends(require_api_key)])
def get_opponent_split_leaderboard(
    opponent_level: str = Query(..., description=f"One of {list(VALID_LEVELS)} -- the tier of opponent these games were against."),
    own_level: str | None = Query(None, description=f"One of {list(VALID_LEVELS)} -- restrict to players whose OWN team is at this tier. Omit for any level."),
    stat: str = Query("points", description=f"One of {list(OPPONENT_SPLIT_STATS)}."),
    min_games: int = Query(3, description="Minimum games played AGAINST that opponent tier specifically, not season-total games."),
    season: str | None = Query(None, description="Defaults to the cache's current season."),
    conference: str | None = Query(None, description="Exact conference match on the player's OWN team. Omit for any conference."),
    top50_only: bool = Query(False, description="Restrict to games against one of the 50 highest-current_rating "
                                                  "teams WITHIN opponent_level (not top 50 nationally)."),
    limit: int = Query(20, le=100),
):
    """Real per-game production filtered to games played against a specific
    opponent tier -- e.g. own_level=High-Major&opponent_level=High-Major for
    'High-Major players who perform best against other High-Major opponents',
    or own_level=Low-Major&opponent_level=High-Major for 'Low-Major players
    who perform best against High-Major competition'. Uses each game's real
    tracked opponent (joined via opponent_team_id -> teams.tier), not a
    season-average approximation. ("P5" is still accepted as an alias for
    High-Major in both level params.) Pass top50_only=true for the "best
    against the top 50 [tier] teams" leaderboards (vs. every team at that
    tier, including its weakest)."""
    conn = get_conn()
    try:
        return opponent_split_leaderboard(conn, own_level=own_level, opponent_level=opponent_level,
                                           stat=stat, min_games=min_games, limit=limit, season=season,
                                           conference=conference, top50_only=top50_only)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()


@app.get("/leaderboards/back-half", dependencies=[Depends(require_api_key)])
def get_back_half_leaderboard(
    level: str | None = Query(None, description=f"One of {list(VALID_LEVELS)}. Omit for the whole league."),
    min_games_per_half: int = Query(5, description="Minimum games required in EACH half of the season to qualify."),
    season: str | None = Query(None, description="Defaults to the cache's current season."),
    limit: int = Query(20, le=100),
    sort: str = Query("ppg", description="Which stat's change ranks the list: ppg, rpg, apg, ts, or all."),
):
    """'Best back half of the season' -- ranks players by how much a given
    stat changed from the first half of their own games played to the
    second half (positive = trending up). `sort` picks ppg/rpg/apg/ts for a
    single ranked list, or "all" to get all 4 rankings in one response
    (`by_sort.ppg`/`.rpg`/`.apg`/`.ts`) from a single DB scan/aggregation --
    prefer "all" over 4 separate calls when a caller wants all 4 lists, since
    the underlying full-season scan is the expensive part and running it 4x
    is what made this section slow enough to time out under real production
    load. See back_half_leaderboard()'s docstring for exactly how the split
    works."""
    conn = get_conn()
    try:
        return back_half_leaderboard(conn, level=level, min_games_per_half=min_games_per_half,
                                      limit=limit, season=season, sort=sort)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()


@app.get("/players/{player_id}/splits", dependencies=[Depends(require_api_key)])
def get_player_splits(player_id: int, season: str | None = Query(None)):
    """This player's game log sliced four ways: by opponent tier (High-
    Major/Mid-Major/Low-Major), against the nation's top 50 rated teams,
    and across just her last 10 games -- powers the profile page's
    opponent-strength breakdown table."""
    conn = get_conn()
    try:
        return player_splits(conn, player_id, season=season)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()


@app.get("/conferences/{conference}/standings", dependencies=[Depends(require_api_key)])
def get_conference_standings(conference: str, season: str | None = Query(None)):
    """Win/loss records (overall and conference-only) for every team in
    one conference this season, sorted by conference win percentage."""
    conn = get_conn()
    try:
        return conference_standings(conn, conference, season=season)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()


@app.get("/games/{game_id}", dependencies=[Depends(require_api_key)])
def get_game_detail(game_id: int):
    """Full box score for one game -- both teams' complete per-player
    lines, plus game metadata (date, score, home/away, OT/neutral-site)."""
    conn = get_conn()
    try:
        return game_detail(conn, game_id)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()


@app.get("/players/{player_id}/game-logs", dependencies=[Depends(require_api_key)])
def get_player_game_logs(player_id: int, season: str | None = Query(None)):
    """Every individual game this player appeared in (optionally filtered
    to one season), most recent first -- powers the expandable per-season
    game log on the player profile page."""
    conn = get_conn()
    try:
        return player_game_logs(conn, player_id, season=season)
    finally:
        conn.close()


@app.get("/teams/{team_id}/schedule", dependencies=[Depends(require_api_key)])
def get_team_schedule(team_id: int, season: str | None = Query(None)):
    """This team's full schedule/results (optionally filtered to one
    season), most recent first -- powers the team profile's Schedule tab."""
    conn = get_conn()
    try:
        return team_schedule(conn, team_id, season=season)
    finally:
        conn.close()
