"""Summit TPE transfer-calculator API. Thin REST wrapper around
projection.py + the summit_tpe_cache.sqlite built by build_cache.py --
simple enough for a website today and a mobile app later, since both just
speak JSON over HTTP rather than needing this logic ported into each
client.
 
Run:
    uvicorn api:app --reload --port 8000
 
Then, e.g.:
    GET /players?search=troxell
    GET /teams?tier=P5
    GET /teams/4/roles
    GET /project?player_id=1234&target_team_id=4&minutes=28
    GET /project?player_id=1234&target_team_id=4&role=starter
 
Interactive docs (auto-generated by FastAPI) at /docs once it's running.
 
---- Access control (env-driven, safe by default for local dev) ----
 
Two env vars control who can reach this API once it's not just running on
your own machine:
 
  SUMMIT_TPE_API_KEY
      If set, every route except /health requires a matching
      "X-API-Key: <value>" request header, or it 401s. If UNSET (the
      default), no key is required at all -- so local `curl`/`/docs`
      testing keeps working with zero setup. Generate one with e.g.
      `python -c "import secrets; print(secrets.token_urlsafe(32))"` and
      set it as an environment variable on whatever host runs this, then
      give the same value to your frontend to send on every request.
 
  SUMMIT_TPE_ALLOWED_ORIGINS
      Comma-separated list of origins allowed to call this API from a
      browser (e.g. "https://mysite.com,https://www.mysite.com"). Defaults
      to "*" (any origin) for local dev. Set this to your real domain(s)
      before a real website points at this API -- "*" plus no API key is
      an open API to the entire internet.
 
Neither is required to run this locally. Both print a startup warning if
left at their insecure defaults, so it's obvious in the logs (not just in
this docstring) that they haven't been configured yet.
"""
 
import os
import secrets
import sqlite3
from pathlib import Path
 
from fastapi import Body, Depends, FastAPI, Header, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
 
from projection import (
    CATEGORY_INFO, LEADERBOARD_STATS, ProjectionError, ROLE_NAMES, VALID_LEVELS, find_fits, leaderboard,
    player_trajectory, project_batch, project_player, standout_projections, team_needs, team_roles,
)
 
DB_PATH = Path(__file__).parent / "summit_tpe_cache.sqlite"
 
API_KEY = os.environ.get("SUMMIT_TPE_API_KEY") or None
ALLOWED_ORIGINS = [o.strip() for o in os.environ.get("SUMMIT_TPE_ALLOWED_ORIGINS", "*").split(",") if o.strip()] or ["*"]
 
app = FastAPI(title="Summit TPE API", version="1.0")
 
app.add_middleware(
    CORSMiddleware, allow_origins=ALLOWED_ORIGINS, allow_methods=["GET", "POST"], allow_headers=["*"],
)
 
 
@app.on_event("startup")
def _warn_if_insecure():
    if API_KEY is None:
        print("[summit-tpe-api] WARNING: SUMMIT_TPE_API_KEY is not set -- every route is open to "
              "anyone who can reach this host. Fine for local dev, not fine once this is reachable "
              "from the internet.")
    if ALLOWED_ORIGINS == ["*"]:
        print("[summit-tpe-api] WARNING: SUMMIT_TPE_ALLOWED_ORIGINS is not set -- CORS allows "
              "requests from ANY website. Set it to your real domain(s) before going live.")
 
 
def require_api_key(x_api_key: str | None = Header(None)):
    """FastAPI dependency, applied to every route below except /health.
    No-ops entirely if SUMMIT_TPE_API_KEY isn't set (local dev default)."""
    if API_KEY is None:
        return
    if x_api_key is None or not secrets.compare_digest(x_api_key, API_KEY):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
 
 
def get_conn():
    if not DB_PATH.exists():
        raise HTTPException(status_code=503, detail=f"{DB_PATH.name} not found -- run build_cache.py first.")
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn
 
 
@app.get("/health")
def health():
    exists = DB_PATH.exists()
    season = None
    if exists:
        conn = get_conn()
        row = conn.execute("SELECT value FROM meta WHERE key='season'").fetchone()
        season = row[0] if row else None
        conn.close()
    return {"ok": exists, "cache_present": exists, "season": season}
 
 
@app.get("/teams", dependencies=[Depends(require_api_key)])
def list_teams(
    tier: str | None = Query(None, description="Filter by tier: P5, Mid-Major, or Low-Major"),
    conference: str | None = Query(None),
    search: str | None = Query(None, description="Case-insensitive substring match on team name"),
    limit: int = Query(100, le=500),
    offset: int = 0,
):
    conn = get_conn()
    clauses, params = [], []
    if tier:
        clauses.append("tier = ?")
        params.append(tier)
    if conference:
        clauses.append("conference = ?")
        params.append(conference)
    if search:
        clauses.append("name LIKE ?")
        params.append(f"%{search}%")
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    rows = conn.execute(
        f"SELECT team_id, name, division, conference, tier, current_rating, sos "
        f"FROM teams {where} ORDER BY current_rating DESC LIMIT ? OFFSET ?",
        params + [limit, offset],
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]
 
 
@app.get("/teams/{team_id}", dependencies=[Depends(require_api_key)])
def get_team_detail(team_id: int):
    conn = get_conn()
    row = conn.execute("SELECT * FROM teams WHERE team_id = ?", (team_id,)).fetchone()
    conn.close()
    if row is None:
        raise HTTPException(status_code=404, detail=f"No team with id {team_id}")
    return dict(row)
 
 
@app.get("/teams/{team_id}/roles", dependencies=[Depends(require_api_key)])
def get_team_roles(team_id: int):
    """Role-based minutes for this team, computed from its own current
    roster (Starter/Sixth Man/Role Player/Depth Piece) -- lets a UI show a
    coach e.g. 'Starter (31.2 min)' as a pickable option before running
    /project with role=starter, instead of only a free-text minutes field."""
    conn = get_conn()
    team = conn.execute("SELECT team_id, name FROM teams WHERE team_id = ?", (team_id,)).fetchone()
    if team is None:
        conn.close()
        raise HTTPException(status_code=404, detail=f"No team with id {team_id}")
    roles = team_roles(conn, team_id)
    conn.close()
    # team_roles() already includes team_id in its return dict -- passing
    # team_id=team_id here too used to raise "dict() got multiple values
    # for keyword argument 'team_id'" on EVERY call (found by actually
    # exercising this endpoint against the live cache, not just reading
    # the code -- it 500'd for every team tested, not just some).
    return dict(team_name=team["name"], **roles)
 
 
@app.get("/players", dependencies=[Depends(require_api_key)])
def list_players(
    search: str | None = Query(None, description="Case-insensitive substring match on player name"),
    team_id: int | None = None,
    position: str | None = None,
    limit: int = Query(50, le=500),
    offset: int = 0,
):
    conn = get_conn()
    clauses, params = [], []
    if search:
        clauses.append("p.name LIKE ?")
        params.append(f"%{search}%")
    if team_id is not None:
        clauses.append("p.team_id = ?")
        params.append(team_id)
    if position:
        clauses.append("p.position = ?")
        params.append(position)
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    rows = conn.execute(
        # Sort by hoop_score_raw (unclamped), not hoop_score (the displayed,
        # 30-99-clamped value) -- several distinct elite seasons legitimately
        # round to the same displayed 99.0 by design (see summit_calc.py's
        # scale_to_hoopscore), so sorting on the displayed value ties players
        # who aren't actually tied and orders them arbitrarily.
        f"""SELECT p.player_id, p.name, p.team_id, t.name AS team_name, t.tier, p.position,
                   p.class_year, p.games, p.ppg, p.rpg, p.apg, p.bpg, p.spg, p.topg, p.hoop_score
            FROM players p LEFT JOIN teams t ON p.team_id = t.team_id
            {where} ORDER BY p.hoop_score_raw DESC LIMIT ? OFFSET ?""",
        params + [limit, offset],
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]
 
 
@app.get("/players/{player_id}", dependencies=[Depends(require_api_key)])
def get_player_detail(player_id: int):
    conn = get_conn()
    row = conn.execute(
        """SELECT p.*, t.name AS team_name, t.tier AS team_tier
           FROM players p LEFT JOIN teams t ON p.team_id = t.team_id
           WHERE p.player_id = ?""",
        (player_id,),
    ).fetchone()
    conn.close()
    if row is None:
        raise HTTPException(status_code=404, detail=f"No player with id {player_id}")
    return dict(row)
 
 
@app.get("/project", dependencies=[Depends(require_api_key)])
def project(
    player_id: int,
    target_team_id: int,
    minutes: float | None = Query(None, description="Exact coach-specified minutes (0-40). Wins over "
                                                       "`role` if both are given."),
    role: str | None = Query(None, description=f"One of {ROLE_NAMES} -- resolved from the target team's "
                                                 f"own current roster via /teams/{{id}}/roles. Ignored if "
                                                 f"`minutes` is also given."),
):
    conn = get_conn()
    try:
        result = project_player(conn, player_id, target_team_id, minutes_override=minutes, role=role)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
    return result
 
 
@app.get("/teams/{team_id}/needs", dependencies=[Depends(require_api_key)])
def get_team_needs(
    team_id: int,
    top_n: int = Query(3, ge=1, le=len(CATEGORY_INFO), description="How many weakest categories to call out"),
    level: str | None = Query(
        None, description=f"One of {list(VALID_LEVELS)}. Restrict the comparison group to teams at that "
                           f"tier only, instead of the whole league (default). E.g. level=Low-Major judges "
                           f"a Low-Major team's weaknesses against other Low-Major rosters, not P5 ones."),
):
    """This team's roster-weighted stat profile (rebounding, assists,
    blocks, steals, turnovers, shooting) vs. a peer group (whole league by
    default, or one tier if `level` is given), ranked worst-to-best. Feeds
    /teams/{team_id}/fits' default `stat` (that internal call always uses
    the whole league, regardless of what's passed here)."""
    conn = get_conn()
    try:
        return team_needs(conn, team_id, top_n=top_n, level=level)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
 
 
@app.get("/teams/{team_id}/fits", dependencies=[Depends(require_api_key)])
def get_team_fits(
    team_id: int,
    stat: str | None = Query(None, description=f"One of {list(CATEGORY_INFO)}. Omit to auto-pick this "
                                                 f"team's single biggest weakness from /teams/{{id}}/needs "
                                                 f"(that auto-pick is always league-wide, regardless of `level`). "
                                                 f"Ignored if `stats` is also given."),
    stats: list[str] | None = Query(
        None, description=f"Repeat for more than one category at once, e.g. "
                           f"?stats=per40_reb&stats=per40_blk -- one of {list(CATEGORY_INFO)} each. Ranks by "
                           f"the average of each candidate's league-wide z-score across all given categories "
                           f"(sign-flipped for turnovers) instead of a single raw value. Wins over `stat`."),
    limit: int = Query(15, le=100),
    min_games: int = Query(5, description="Exclude candidates with a thinner sample than this many games"),
    transfer_portal_only: bool = Query(
        False, description="Only include candidates confirmed in the transfer portal. Requires a "
                            "'Transfer Portal' column on the Players sheet + a rebuilt cache -- errors "
                            "clearly (404) if no transfer portal data has been loaded yet, instead of "
                            "silently returning an empty list."),
    level: str | None = Query(
        None, description=f"One of {list(VALID_LEVELS)}. Only consider candidates whose CURRENT team is "
                           f"at that tier -- e.g. level=Low-Major for a Low-Major team excludes every "
                           f"P5/Mid-Major player from the pool outright, instead of just labeling them."),
    role: str | None = Query(None, description=f"One of {ROLE_NAMES} -- resolved from THIS team's (team_id's) "
                                                f"own current roster via /teams/{{id}}/roles, and applied to "
                                                f"every candidate's projection. Ignored if `minutes` is given."),
    minutes: float | None = Query(None, description="Exact 0-40 minutes applied to every candidate's "
                                                      "projection. Wins over `role` if both are given."),
):
    """Reverse lookup: every player NOT on this roster, ranked by her
    PROJECTED contribution to `stat`/`stats` (or this team's biggest
    weakness, if neither is given) if she transferred in, optionally
    projected at a specific role or exact minutes on THIS team rather
    than each candidate's own auto-projected minutes. Each candidate is
    projected with the exact same math as /project, just run over the
    whole player pool at once. Every candidate includes current_division,
    current_tier/level, and class_year. By default this is a plain ranking
    by projected production, not filtered by recruiting realism -- pass
    `level` to restrict the candidate pool to one tier instead of just
    labeling unrealistic candidates (a P5 starter, etc) for manual skip."""
    conn = get_conn()
    try:
        return find_fits(conn, team_id, stat=stat, stats=stats, limit=limit, min_games=min_games,
                          transfer_portal_only=transfer_portal_only, level=level, role=role, minutes=minutes)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
 
 
class BatchPlayerRequest(BaseModel):
    player_id: int
    minutes: float | None = None
    role: str | None = None
 
 
class BatchProjectRequest(BaseModel):
    target_team_id: int
    players: list[BatchPlayerRequest]
 
 
@app.post("/project/batch", dependencies=[Depends(require_api_key)])
def project_batch_endpoint(body: BatchProjectRequest = Body(...)):
    """Project several players at the same target team in one call, plus
    a combined per-game total across all of them -- for evaluating a
    shortlist of transfer targets against open roster spots at once,
    instead of one /project call per name. See project_batch()'s
    docstring for exactly what the combined total does and doesn't mean
    (it's a sum of individual projections, not a re-solved team rating)."""
    conn = get_conn()
    try:
        result = project_batch(
            conn, body.target_team_id,
            [dict(player_id=p.player_id, minutes=p.minutes, role=p.role) for p in body.players],
        )
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
    return result
 
 
@app.get("/players/{player_id}/trajectory", dependencies=[Depends(require_api_key)])
def get_player_trajectory(player_id: int):
    """Season-by-season profile for this player across every season in
    the workbook (not just the current one), with a simple Improving /
    Declining / Stable label -- for telling apart two players with a
    similar current-season line but very different trends."""
    conn = get_conn()
    try:
        return player_trajectory(conn, player_id)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()

@app.get("/leaderboards/players", dependencies=[Depends(require_api_key)])
def get_player_leaderboard(
    stat: str = Query("hoop_score", description=f"One of {list(LEADERBOARD_STATS)}."),
    level: str | None = Query(None, description=f"One of {list(VALID_LEVELS)}. Omit for the whole league."),
    division: str | None = Query(None, description="D1 or D2 (as recorded on the Teams sheet). Omit for both."),
    min_games: int = Query(5, description="Exclude players with a thinner sample than this many games."),
    limit: int = Query(25, le=100),
):
    """A real, no-projection leaderboard -- top players this season by one
    stat (or lowest, for turnovers), optionally restricted to a tier
    and/or division. This is what actually happened, not a what-if."""
    conn = get_conn()
    try:
        return leaderboard(conn, stat=stat, level=level, division=division, min_games=min_games, limit=limit)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()


@app.get("/leaderboards/standouts", dependencies=[Depends(require_api_key)])
def get_standouts_leaderboard(
    level: str = Query(..., description=f"One of {list(VALID_LEVELS)} -- the level these players currently play at."),
    target_level: str = Query("P5", description=f"One of {list(VALID_LEVELS)} -- the level to project them at."),
    min_games: int = Query(8, description="Exclude players with a thinner sample than this many games."),
    limit: int = Query(20, le=100),
):
    """'Who from a lower level projects best at the top level' -- every
    player currently at `level`, projected against a SYNTHETIC team at
    `target_level` (the live average current_rating of every real team at
    that tier this season, not any single school), ranked by projected
    Hoop Score. See synthetic_target_note in the response for exactly
    what was used -- this is a directional read, not a projection at any
    specific real program."""
    conn = get_conn()
    try:
        return standout_projections(conn, level=level, target_level=target_level,
                                     min_games=min_games, limit=limit)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
