"""Summit TPE transfer-calculator API. Thin REST wrapper around
projection.py + the summit_tpe_cache.sqlite built by build_cache.py --
simple enough for a website today and a mobile app later, since both just
speak JSON over HTTP rather than needing this logic ported into each
client.

Run:
    uvicorn api:app --reload --port 8000

Then, e.g.:
    GET /players?search=troxell
    GET /teams?tier=P5
    GET /teams/4/roles
    GET /project?player_id=1234&target_team_id=4&minutes=28
    GET /project?player_id=1234&target_team_id=4&role=starter

Interactive docs (auto-generated by FastAPI) at /docs once it's running.
"""

import sqlite3
from pathlib import Path

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from projectionOLD import ProjectionError, ROLE_NAMES, project_player, team_roles

DB_PATH = Path(__file__).parent / "summit_tpe_cache.sqlite"

app = FastAPI(title="Summit TPE API", version="1.0")

# Permissive CORS since a browser-based site/app is the intended client.
# Tighten allow_origins to your actual domain(s) before going to production.
app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_methods=["GET"], allow_headers=["*"],
)


def get_conn():
    if not DB_PATH.exists():
        raise HTTPException(status_code=503, detail=f"{DB_PATH.name} not found -- run build_cache.py first.")
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


@app.get("/health")
def health():
    exists = DB_PATH.exists()
    season = None
    if exists:
        conn = get_conn()
        row = conn.execute("SELECT value FROM meta WHERE key='season'").fetchone()
        season = row[0] if row else None
        conn.close()
    return {"ok": exists, "cache_present": exists, "season": season}


@app.get("/teams")
def list_teams(
    tier: str | None = Query(None, description="Filter by tier: P5, Mid-Major, or Low-Major"),
    conference: str | None = Query(None),
    search: str | None = Query(None, description="Case-insensitive substring match on team name"),
    limit: int = Query(100, le=500),
    offset: int = 0,
):
    conn = get_conn()
    clauses, params = [], []
    if tier:
        clauses.append("tier = ?")
        params.append(tier)
    if conference:
        clauses.append("conference = ?")
        params.append(conference)
    if search:
        clauses.append("name LIKE ?")
        params.append(f"%{search}%")
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    rows = conn.execute(
        f"SELECT team_id, name, division, conference, tier, current_rating, sos "
        f"FROM teams {where} ORDER BY current_rating DESC LIMIT ? OFFSET ?",
        params + [limit, offset],
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


@app.get("/teams/{team_id}")
def get_team_detail(team_id: int):
    conn = get_conn()
    row = conn.execute("SELECT * FROM teams WHERE team_id = ?", (team_id,)).fetchone()
    conn.close()
    if row is None:
        raise HTTPException(status_code=404, detail=f"No team with id {team_id}")
    return dict(row)


@app.get("/teams/{team_id}/roles")
def get_team_roles(team_id: int):
    """Role-based minutes for this team, computed from its own current
    roster (Starter/Sixth Man/Role Player/Depth Piece) -- lets a UI show a
    coach e.g. 'Starter (31.2 min)' as a pickable option before running
    /project with role=starter, instead of only a free-text minutes field."""
    conn = get_conn()
    team = conn.execute("SELECT team_id, name FROM teams WHERE team_id = ?", (team_id,)).fetchone()
    if team is None:
        conn.close()
        raise HTTPException(status_code=404, detail=f"No team with id {team_id}")
    roles = team_roles(conn, team_id)
    conn.close()
    return dict(team_id=team_id, team_name=team["name"], **roles)


@app.get("/players")
def list_players(
    search: str | None = Query(None, description="Case-insensitive substring match on player name"),
    team_id: int | None = None,
    position: str | None = None,
    limit: int = Query(50, le=500),
    offset: int = 0,
):
    conn = get_conn()
    clauses, params = [], []
    if search:
        clauses.append("p.name LIKE ?")
        params.append(f"%{search}%")
    if team_id is not None:
        clauses.append("p.team_id = ?")
        params.append(team_id)
    if position:
        clauses.append("p.position = ?")
        params.append(position)
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    rows = conn.execute(
        # Sort by hoop_score_raw (unclamped), not hoop_score (the displayed,
        # 30-99-clamped value) -- several distinct elite seasons legitimately
        # round to the same displayed 99.0 by design (see summit_calc.py's
        # scale_to_hoopscore), so sorting on the displayed value ties players
        # who aren't actually tied and orders them arbitrarily.
        f"""SELECT p.player_id, p.name, p.team_id, t.name AS team_name, t.tier, p.position,
                   p.class_year, p.games, p.ppg, p.rpg, p.apg, p.bpg, p.spg, p.topg, p.hoop_score
            FROM players p LEFT JOIN teams t ON p.team_id = t.team_id
            {where} ORDER BY p.hoop_score_raw DESC LIMIT ? OFFSET ?""",
        params + [limit, offset],
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


@app.get("/players/{player_id}")
def get_player_detail(player_id: int):
    conn = get_conn()
    row = conn.execute(
        """SELECT p.*, t.name AS team_name, t.tier AS team_tier
           FROM players p LEFT JOIN teams t ON p.team_id = t.team_id
           WHERE p.player_id = ?""",
        (player_id,),
    ).fetchone()
    conn.close()
    if row is None:
        raise HTTPException(status_code=404, detail=f"No player with id {player_id}")
    return dict(row)


@app.get("/project")
def project(
    player_id: int,
    target_team_id: int,
    minutes: float | None = Query(None, description="Exact coach-specified minutes (0-40). Wins over "
                                                       "`role` if both are given."),
    role: str | None = Query(None, description=f"One of {ROLE_NAMES} -- resolved from the target team's "
                                                 f"own current roster via /teams/{{id}}/roles. Ignored if "
                                                 f"`minutes` is also given."),
):
    conn = get_conn()
    try:
        result = project_player(conn, player_id, target_team_id, minutes_override=minutes, role=role)
    except ProjectionError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    finally:
        conn.close()
    return result
